# Numpy
 The fundamental package for scientific computing with python

In [ ]:
! pip install numpy

In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.25.2'

# N-dimensional Array in Numpy

In [ ]:
# one dimensional array using list

In [ ]:
x = np.array([2, 3, 4, 5])
x

array([2, 3, 4, 5])

In [ ]:
type(x) # ndarray means n dimensional array

numpy.ndarray

In [ ]:
x.ndim # it is a one dimensional array

1

In [ ]:
x.shape

(4,)

In [ ]:
len(x)

4

In [ ]:
x.dtype

dtype('int64')

# Indexing and slicing

In [ ]:
x = np.array([2, 3, 4, 5, 8, 2, 0, 3])
x

array([2, 3, 4, 5, 8, 2, 0, 3])

In [ ]:
x[6]

0

In [ ]:
x[4:7]

array([8, 2, 0])

In [ ]:
x[-2]

0

# Difference between list and array

* array supports homogenous datatype while list supports multiple data type
* array are faster than list
* array are memory efficient than list

In [ ]:
data = [True, 0, 44.5, 'hello']
type(data[0])

bool

In [ ]:
x = np.array(data)
x

array(['True', '0', '44.5', 'hello'], dtype='<U32')

In [ ]:
type(x[0])

numpy.str_

In [ ]:
# memory efficient


In [ ]:
x = np.ones(5, dtype=np.int8) # i can control dtype in array
x

array([1, 1, 1, 1, 1], dtype=int8)

In [ ]:
np.zeros(3, dtype=np.float16)

array([0., 0., 0.], dtype=float16)

In [ ]:
np.arange(1, 15, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
list(range(1, 15, 1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

# .linspace

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
a = np.array([8, 9])
b = np.array([2, 3])

In [ ]:
a + b

array([10, 12])

In [ ]:
np.concatenate([a, b])

array([8, 9, 2, 3])

# broadcasting

In [ ]:
x = np.array([8, 6])
2 * x

array([16, 12])

In [ ]:
x.ndim

1

# Statistics using numpy

In [ ]:
np.random.randint(low=1, high=100)

48

In [ ]:
np.random.seed(0) # seed>=0
np.random.randint(low=1, high=100)

45

In [ ]:
np.random.seed(0) # seed>=0
np.random.randint(low=1, high=100, size=10)
x

array([8, 6])

In [ ]:
np.mean(x)

7.0

In [ ]:
np.median(x)

7.0

In [ ]:
from scipy.stats import mode

In [ ]:
mode(x)

ModeResult(mode=6, count=1)

In [ ]:
np.std(x)

1.0

In [ ]:
np.var(x)

1.0

In [ ]:
np.min(x)

6